name: toponomy_app
description: "A new Flutter project."

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  path_provider: ^2.0.15
  sqflite: ^2.3.2
  http: ^1.2.0
  provider: ^6.1.1
  shared_preferences: ^2.0.11
  google_maps_flutter: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

